// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP20GcGVjyVovYaE1Rq-8V-Phr8A7NdPQ',
    appId: '1:748233791562:web:9ea75b70cdedb8c33aaeb3',
    messagingSenderId: '748233791562',
    projectId: 'flutter-instagram-clone-4748b',
    authDomain: 'flutter-instagram-clone-4748b.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-4748b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1nYpO6N86lGC8UhC1ii0rAKPJgxrG2Fw',
    appId: '1:748233791562:android:f7f6862cb8cb170d3aaeb3',
    messagingSenderId: '748233791562',
    projectId: 'flutter-instagram-clone-4748b',
    storageBucket: 'flutter-instagram-clone-4748b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSavekhw6aWUj3LGBNUKr1sVnyeFzZqD4',
    appId: '1:748233791562:ios:00e95e25613b4c9a3aaeb3',
    messagingSenderId: '748233791562',
    projectId: 'flutter-instagram-clone-4748b',
    storageBucket: 'flutter-instagram-clone-4748b.firebasestorage.app',
    iosClientId: '748233791562-0oetl8frohupnfd6hkcc2i9hqdap87pm.apps.googleusercontent.com',
    iosBundleId: 'com.dnguyen.flutterInstagramClone.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSavekhw6aWUj3LGBNUKr1sVnyeFzZqD4',
    appId: '1:748233791562:ios:00e95e25613b4c9a3aaeb3',
    messagingSenderId: '748233791562',
    projectId: 'flutter-instagram-clone-4748b',
    storageBucket: 'flutter-instagram-clone-4748b.firebasestorage.app',
    iosClientId: '748233791562-0oetl8frohupnfd6hkcc2i9hqdap87pm.apps.googleusercontent.com',
    iosBundleId: 'com.dnguyen.flutterInstagramClone.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP20GcGVjyVovYaE1Rq-8V-Phr8A7NdPQ',
    appId: '1:748233791562:web:8834667c4e5744d43aaeb3',
    messagingSenderId: '748233791562',
    projectId: 'flutter-instagram-clone-4748b',
    authDomain: 'flutter-instagram-clone-4748b.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-4748b.firebasestorage.app',
  );
}
