// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSePK2lGLbQmMt3aHxv8jpz7lSFxZLhsk',
    appId: '1:896686666481:web:90ff8c7a42aed3d01d6f50',
    messagingSenderId: '896686666481',
    projectId: 'flutter-instagram-clone-44f8a',
    authDomain: 'flutter-instagram-clone-44f8a.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-44f8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECnLtBmupYy4kpCeDKiyfeG9pcjO1qYg',
    appId: '1:896686666481:android:2c2227f905385ecf1d6f50',
    messagingSenderId: '896686666481',
    projectId: 'flutter-instagram-clone-44f8a',
    storageBucket: 'flutter-instagram-clone-44f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_bo_tmTSDAQ_9mMh7jkKENGID0SnciQ',
    appId: '1:896686666481:ios:9e78ea74dc8a12df1d6f50',
    messagingSenderId: '896686666481',
    projectId: 'flutter-instagram-clone-44f8a',
    storageBucket: 'flutter-instagram-clone-44f8a.firebasestorage.app',
    iosClientId: '896686666481-gcl2ha6mgpodn4mrbj9420l5118qgakk.apps.googleusercontent.com',
    iosBundleId: 'com.dnguyen.flutterInstagramClone.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_bo_tmTSDAQ_9mMh7jkKENGID0SnciQ',
    appId: '1:896686666481:ios:9e78ea74dc8a12df1d6f50',
    messagingSenderId: '896686666481',
    projectId: 'flutter-instagram-clone-44f8a',
    storageBucket: 'flutter-instagram-clone-44f8a.firebasestorage.app',
    iosClientId: '896686666481-gcl2ha6mgpodn4mrbj9420l5118qgakk.apps.googleusercontent.com',
    iosBundleId: 'com.dnguyen.flutterInstagramClone.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSePK2lGLbQmMt3aHxv8jpz7lSFxZLhsk',
    appId: '1:896686666481:web:14851c48017d9bba1d6f50',
    messagingSenderId: '896686666481',
    projectId: 'flutter-instagram-clone-44f8a',
    authDomain: 'flutter-instagram-clone-44f8a.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-44f8a.firebasestorage.app',
  );
}
