// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqospv_p5zYYnkkNLrvIOan0YBY3fX1s',
    appId: '1:1021979341460:web:0ed8ec88555eb5b4a43a81',
    messagingSenderId: '1021979341460',
    projectId: 'flutter-instagram-clone-774b5',
    authDomain: 'flutter-instagram-clone-774b5.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-774b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjKZKw4ds9FlIhIj-yDjuTGhJhWfKXhGg',
    appId: '1:1021979341460:android:aae0397af0869988a43a81',
    messagingSenderId: '1021979341460',
    projectId: 'flutter-instagram-clone-774b5',
    storageBucket: 'flutter-instagram-clone-774b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAauPwy79Ui_Q-12M25V-WR_hh_-GhHeEg',
    appId: '1:1021979341460:ios:b8bc8e5d983e8649a43a81',
    messagingSenderId: '1021979341460',
    projectId: 'flutter-instagram-clone-774b5',
    storageBucket: 'flutter-instagram-clone-774b5.firebasestorage.app',
    iosBundleId: 'com.dnguyen.flutterInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAauPwy79Ui_Q-12M25V-WR_hh_-GhHeEg',
    appId: '1:1021979341460:ios:b8bc8e5d983e8649a43a81',
    messagingSenderId: '1021979341460',
    projectId: 'flutter-instagram-clone-774b5',
    storageBucket: 'flutter-instagram-clone-774b5.firebasestorage.app',
    iosBundleId: 'com.dnguyen.flutterInstagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAqospv_p5zYYnkkNLrvIOan0YBY3fX1s',
    appId: '1:1021979341460:web:d14e680a1ded6909a43a81',
    messagingSenderId: '1021979341460',
    projectId: 'flutter-instagram-clone-774b5',
    authDomain: 'flutter-instagram-clone-774b5.firebaseapp.com',
    storageBucket: 'flutter-instagram-clone-774b5.firebasestorage.app',
  );

}